name: yfokon
base: core22
build-base: core22
version: 0.8.2
summary: Gestionnaire de tâches moderne et rapide.
description: |
  Yfokon est une application open-source permettant de gérer facilement ses tâches avec une interface moderne et fluide.
grade: stable
confinement: strict
compression: lzo

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  yfokon:
    command: usr/bin/yfokon
    desktop: usr/share/applications/yfokon.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - pulseaudio
      - wayland
      - x11
    #plugs:
    #  - network
    # Add whatever plugs you need here, see https://snapcraft.io/docs/snapcraft-interfaces for more info.
    # The gnome extension already includes [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service ]
    #  - single-instance-plug # add this if you're using the single-instance plugin
    #slots:
    # Add the slots you need to expose to other snaps
    #  - single-instance-plug # add this if you're using the single-instance plugin

# Add these lines only if you're using the single-instance plugin
# Check https://v2.tauri.app/plugin/single-instance/ for details
#slots:
#  single-instance:
#    interface: dbus
#    bus: session
#    name: org.net_mydomain_MyApp.SingleInstance # Remember to change net_mydomain_MyApp to your app ID with "_" instead of "." and "-"
#
#plugs:
#  single-instance-plug:
#    interface: dbus
#    bus: session
#    name: org.net_mydomain_MyApp.SingleInstance # Remember to change net_mydomain_MyApp to your app ID with "_" instead of "." and "-"

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eux

      curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      source ~/.bashrc
      nvm install --lts

      rm -rf node_modules package-lock.json

      rustup default stable

      npm install

      npm run tauri build -- --bundles deb

      DEB_DIR=$(ls -dt src-tauri/target/release/bundle/deb/*/ | head -n 1)
      echo "Utilisation du dossier : $DEB_DIR"

      DESKTOP_FILE=$(find "$DEB_DIR/data/usr/share/applications" -name '*.desktop' | head -n 1 || true)
      if [ -z "$DESKTOP_FILE" ]; then
          echo "❌ Aucun .desktop trouvé dans $DEB_DIR"
          exit 1
      fi
      echo "Desktop trouvé : $DESKTOP_FILE"

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp "$DESKTOP_FILE" $SNAPCRAFT_PART_INSTALL/usr/share/applications/yfokon.desktop

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps
      cp "$DEB_DIR/data/usr/share/icons/hicolor/32x32/apps/yfokon.png" $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps/yfokon.png

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp "$DEB_DIR/data/usr/bin/yfokon" $SNAPCRAFT_PART_INSTALL/usr/bin/yfokon

      sed -i -e 's|^Icon=.*|Icon=/usr/share/icons/hicolor/32x32/apps/yfokon.png|' \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/yfokon.desktop