name: Build/Deploy

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Runner OS
        run:
          echo ${{ runner.os }}
      - name: Get Repo
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 23

        if: runner.os != 'Linux'
      - name: Set Linux env variable
        run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}

        if: runner.os != 'Windows'
      - name: Set Windows env variable
        run: set GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        # run:  |
        #   if "$RUNNER_OS" == "Linux";
        #       export GH_TOKEN=${{ secrets.GITHUB_TOKEN }};
        #   if "$RUNNER_OS" == "Windows";
        #       set GH_TOKEN=${{ secrets.GITHUB_TOKEN }};

      - name: Install Dependencies
        run: npm install

      # - name: Build/release Electron app
      #   uses: samuelmeuli/action-electron-builder@v1.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Deploy
        run: npm run deploy:$RUNNER_OS