name: Build/Deploy

on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Get Repo
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install Dependencies
        run: npm install
        
      - name: Build and Deploy
        run: npm run deploy:$RUNNER_OS