name: Build/Deploy

on: workflow_dispatch

env:
  GH_TOKEN: secrets.GITHUB_TOKEN

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Get Repo
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install Dependencies
        run: npm install

      # - name: Build/release Electron app
      #   uses: samuelmeuli/action-electron-builder@v1.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Deploy
        run: npm run deploy:$RUNNER_OS