name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Print OS name
        shell: bash
        run: |
          echo "$RUNNER_OS"
    #   - name: Check out Git repository
    #     uses: actions/checkout@v1

    #   - name: Install Node.js, NPM and Yarn
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: 10

    #   - name: Install Dependencies
    #     run: npm install

    #   - name: Build and Deploy
    #     run: npm run deploy